version: "3.9"

services:
  php:
    container_name: "${PROJECT_NAME}_php"
    build:
      context: .
      dockerfile: ./Dockerfile-php
    volumes:
      - ../:/var/www/html
    restart: $RESTART

  nginx:
    container_name: "${PROJECT_NAME}_nginx"
    image: nginx:$NGINX_TAG
    depends_on:
      - php
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    ports:
      - "8080:80"
    # networks:
    #   default:
    #     aliases:
    #       - $PROJECT_BASE_URL
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.${PROJECT_NAME}_nginx.tls=true"
    #   - "traefik.frontend.rule=Host:${PROJECT_BASE_URL}"
    #   - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"
    #   - "traefik.http.middlewares.${PROJECT_NAME}_https_nginx.redirectscheme.scheme=https"
    #   - "traefik.http.routers.${PROJECT_NAME}_https_nginx.entrypoints=websecure"
    #   - "traefik.http.routers.${PROJECT_NAME}_https_nginx.rule=Host(`${PROJECT_BASE_URL}`)"
    #   - "traefik.http.routers.${PROJECT_NAME}_https_nginx.tls=true"
    restart: $RESTART

  mariadb:
    container_name: "${PROJECT_NAME}_mariadb"
    image: mariadb:$MARIADB_TAG
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "${MARIADB_PORT}:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "--user=root", "--password=", "--host=127.0.0.1", "ping", "--silent" ]
      interval: 2s
      timeout: 10s
      retries: 10
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    networks:
      - default
    restart: $RESTART

  phpmyadmin:
    container_name: "${PROJECT_NAME}_phpmyadmin"
    image: phpmyadmin/phpmyadmin:$PHPMYADMIN_TAG
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: $MYSQL_ROOT_PASSWORD
    links:
      - mariadb:mariadb
    ports:
      - "${PHPMYADMIN_PORT}:80"
    restart: $RESTART

  # traefik:
  #   image: traefik:$TRAEFIK_TAG
  #   container_name: "${PROJECT_NAME}_traefik"
  #   command: >-
  #     --api.insecure=true
  #     --providers.docker
  #     --entrypoints.web.address=:80
  #     --entrypoints.websecure.address=:443
  #   ports:
  #     - "8080:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   restart: $RESTART

networks:
  default:
